# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bbannier.github.io" # the base hostname & protocol for your site

permalink: /blog/:categories/:year/:month/:day/:title.html

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Benjamin Bannier blags
  avatar: avatar.png
  gravatar: 621b61c5445afea7639b4cf6bb7c455a # Email MD5 hash
  description: "Benjamin Bannier blogs" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

  # Icons
  rss: false
  email_address: "bbannier@gmail.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: "honk"
  dribbble:
  facebook:
  flickr:
  github: "bbannier"
  google_plus: "u/0/+BenjaminBannier"
  instagram:
  linkedin: "https://www.linkedin.com/in/bbannier" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "https://stackoverflow.com/users/176922/benjamin-bannier" # Full URL
  steam:
  tumblr:
  twitter: "BenjaminBannier"
  wordpress:
  youtube:
  xing: "Benjamin_bannier"

  # Scripts
  google_analytics: "UA-60230498-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "bbannier"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

